// frontends/web-angular/src/app/components/revenue-chart.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  effect,
  type ElementRef,
  inject,
  signal,
  viewChild,
} from '@angular/core';

import { formatCount, formatMad, formatMinute, type SeriesPoint, theme } from '@shared/index';

import { Chart } from '../charts';
import { LiveDashboardService } from '../live-dashboard.service';

type Range = 'minute' | 'hour';

@Component({
  selector: 'app-revenue-chart',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="card">
      <header class="card__header">
        <h2>Revenue &amp; orders</h2>
        <div class="segmented" role="tablist" aria-label="Time range">
          @for (option of ranges; track option.value) {
            <button
              role="tab"
              [class.active]="range() === option.value"
              [attr.aria-selected]="range() === option.value"
              (click)="range.set(option.value)"
            >
              {{ option.label }}
            </button>
          }
        </div>
      </header>
      <div class="chart-canvas"><canvas #canvas aria-label="Revenue and orders over time"></canvas></div>
    </section>
  `,
})
export class RevenueChart {
  private readonly live = inject(LiveDashboardService);
  private readonly canvas = viewChild.required<ElementRef<HTMLCanvasElement>>('canvas');
  private chart: Chart<'line'> | null = null;

  protected readonly ranges = [
    { value: 'minute' as const, label: 'Last 60 min' },
    { value: 'hour' as const, label: 'Last 24 h' },
  ];
  protected readonly range = signal<Range>('minute');
  private readonly points = computed(() =>
    this.range() === 'minute' ? this.live.revenuePerMinute() : this.live.revenuePerHour(),
  );

  constructor() {
    afterNextRender(() => {
      this.chart = new Chart(this.canvas().nativeElement, {
        type: 'line',
        data: {
          labels: [],
          datasets: [
            {
              label: 'Revenue',
              data: [],
              yAxisID: 'mad',
              borderColor: theme.accent,
              backgroundColor: 'rgba(108, 140, 255, 0.18)',
              fill: true,
              tension: 0.35,
              pointRadius: 0,
              borderWidth: 2,
            },
            { label: 'Orders', data: [], yAxisID: 'orders', borderColor: theme.accent2, pointRadius: 0, tension: 0.35 },
            { label: 'Cancelled', data: [], yAxisID: 'orders', borderColor: theme.bad, pointRadius: 0, tension: 0.35 },
          ],
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          interaction: { mode: 'index', intersect: false },
          scales: {
            x: { grid: { display: false }, ticks: { maxTicksLimit: 8 } },
            mad: { position: 'left', grid: { color: theme.grid }, ticks: { callback: (v) => formatMad(Number(v)) } },
            orders: { position: 'right', grid: { display: false } },
          },
          plugins: {
            tooltip: {
              callbacks: {
                label: (item) =>
                  `${item.dataset.label}: ${item.datasetIndex === 0 ? formatMad(item.parsed.y) : formatCount(item.parsed.y)}`,
              },
            },
          },
        },
      });
      this.render(this.points());
    });

    // Runs whenever the selected series changes by value; the chart is updated in place.
    effect(() => {
      const points = this.points();
      if (this.chart) this.render(points);
    });

    inject(DestroyRef).onDestroy(() => this.chart?.destroy());
  }

  private render(points: readonly SeriesPoint[]): void {
    const chart = this.chart;
    if (!chart) return;
    chart.data.labels = points.map((p) => formatMinute(p.bucket));
    const [revenue, orders, cancelled] = chart.data.datasets;
    revenue!.data = points.map((p) => p.revenue_mad);
    orders!.data = points.map((p) => p.orders);
    cancelled!.data = points.map((p) => p.cancelled);
    chart.update('none'); // 'none' = no animation: new data appears without a redraw flash
  }
}

// frontends/web-react/src/components/RevenueChart.tsx
import { memo, useMemo, useState } from 'react';
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

import { formatCount, formatMad, formatMinute, type SeriesPoint, type SnapshotMessage } from '@shared/index';

import { useSnapshot } from '../live/hooks';

type Range = 'minute' | 'hour';

const selectMinutes = (s: SnapshotMessage) => s.revenue_per_minute;
const selectHours = (s: SnapshotMessage) => s.revenue_per_hour;

const compactMad = new Intl.NumberFormat('fr-MA', { notation: 'compact', maximumFractionDigits: 1 });

/**
 * Smooth updates without flicker:
 * - animations are off (an animation restarting every 250 ms is what looks like flicker),
 * - the chart component stays mounted; only its `data` prop changes,
 * - `memo` + React Query structural sharing skip re-renders when the series is unchanged.
 */
const Chart = memo(function Chart({ points }: { points: readonly SeriesPoint[] }) {
  const data = useMemo(
    () => points.map((p) => ({ bucket: p.bucket, revenue: p.revenue_mad, orders: p.orders, cancelled: p.cancelled })),
    [points],
  );
  return (
    <ResponsiveContainer width="100%" height={280}>
      <ComposedChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}>
        <defs>
          <linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor="var(--accent)" stopOpacity={0.35} />
            <stop offset="100%" stopColor="var(--accent)" stopOpacity={0} />
          </linearGradient>
        </defs>
        <CartesianGrid stroke="var(--grid)" vertical={false} />
        <XAxis dataKey="bucket" tickFormatter={formatMinute} minTickGap={40} stroke="var(--muted)" fontSize={12} />
        <YAxis yAxisId="mad" tickFormatter={(v: number) => compactMad.format(v)} stroke="var(--muted)" fontSize={12} width={48} />
        <YAxis yAxisId="orders" orientation="right" stroke="var(--muted)" fontSize={12} width={36} />
        <Tooltip
          contentStyle={{ background: 'var(--surface-2)', border: '1px solid var(--border)', borderRadius: 8 }}
          labelFormatter={(label) => formatMinute(String(label))}
          formatter={(value, name) => [name === 'Revenue' ? formatMad(Number(value)) : formatCount(Number(value)), name]}
        />
        <Area
          yAxisId="mad"
          type="monotone"
          dataKey="revenue"
          name="Revenue"
          stroke="var(--accent)"
          strokeWidth={2}
          fill="url(#revenueFill)"
          isAnimationActive={false}
        />
        <Line yAxisId="orders" type="monotone" dataKey="orders" name="Orders" stroke="var(--accent-2)" dot={false} isAnimationActive={false} />
        <Line yAxisId="orders" type="monotone" dataKey="cancelled" name="Cancelled" stroke="var(--bad)" dot={false} isAnimationActive={false} />
      </ComposedChart>
    </ResponsiveContainer>
  );
});

export function RevenueChart() {
  const [range, setRange] = useState<Range>('minute');
  const { data } = useSnapshot(range === 'minute' ? selectMinutes : selectHours);
  return (
    <section className="card chart">
      <header className="card__header">
        <h2>Revenue &amp; orders</h2>
        <div className="segmented" role="tablist" aria-label="Time range">
          {(['minute', 'hour'] as const).map((r) => (
            <button key={r} role="tab" aria-selected={range === r} className={range === r ? 'active' : ''} onClick={() => setRange(r)}>
              {r === 'minute' ? 'Last 60 min' : 'Last 24 h'}
            </button>
          ))}
        </div>
      </header>
      {data ? <Chart points={data} /> : <div className="placeholder">Waiting for data…</div>}
    </section>
  );
}
